server:
  port: 8080

parquet:
  file:
    download:
      location: file:./datasets/taxitrips/trips_dats.parquet
spring:
  application:
    name: taxi-trips-analytics-service

logging:
  level:
    com.xyztaxicompany.analytics.trips: INFO

s2cellId:
  level: 16